### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'address')

### ISSUE THREAD

**Issue by coinvf** [5ire-tech/wasm-contract-deployment#13]
Hello!
[wasm-contract-deployment](https://github.com/5ire-tech/wasm-contract-deployment) error

PS D:\GIT\wasm-contract-deployment> node deploy.js
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 10.1.11     node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/keyring/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 6.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/keyring/node_modules/@polkadot/wasm-crypto/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 10.1.11     node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/keyring/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/api-derive/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 6.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/keyring/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api-derive/node_modules/@polkadot/wasm-crypto/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 10.1.11     node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/keyring/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/api-derive/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/api/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 6.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/keyring/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api-derive/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api/node_modules/@polkadot/wasm-crypto/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 10.1.11     node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/keyring/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/api-derive/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/api/node_modules/@polkadot/util-crypto/
        esm 10.1.11     node_modules/@polkadot/api-contract/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 6.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/keyring/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api-derive/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api-contract/node_modules/@polkadot/wasm-crypto/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        10.1.11 /D:/GIT/wasm-contract-deployment/node_modules/@polkadot/util/
        7.9.2   <unknown>
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        10.1.11 /D:/GIT/wasm-contract-deployment/node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
        10.1.11 /D:/GIT/wasm-contract-deployment/node_modules/@polkadot/keyring/node_modules/@polkadot/util-crypto/
        10.1.11 /D:/GIT/wasm-contract-deployment/node_modules/@polkadot/api-derive/node_modules/@polkadot/util-crypto/
        10.1.11 /D:/GIT/wasm-contract-deployment/node_modules/@polkadot/api/node_modules/@polkadot/util-crypto/
        10.1.11 /D:/GIT/wasm-contract-deployment/node_modules/@polkadot/api-contract/node_modules/@polkadot/util-crypto/
        7.9.2   <unknown>
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 6.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/keyring/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api-derive/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api/node_modules/@polkadot/wasm-crypto/
        esm 6.3.1       node_modules/@polkadot/api-contract/node_modules/@polkadot/wasm-crypto/
        esm 4.6.1       node_modules/@polkadot/wasm-crypto/
file:///D:/GIT/wasm-contract-deployment/deploy.js:60
        address = response.contract.address.toString();
                                    ^

TypeError: Cannot read properties of undefined (reading 'address')
    at file:///D:/GIT/wasm-contract-deployment/deploy.js:60:37
    at file:///D:/GIT/wasm-contract-deployment/node_modules/@polkadot/api/promise/decorateMethod.js:61:22
    at file:///D:/GIT/wasm-contract-deployment/node_modules/@polkadot/util/nextTick.js:14:7

**Comment by dung5ire** [comment]
Please give us your address

**Comment by coinvf** [comment]
> Please give us your address

my address:  5HLMC1vNUA3TgdoqppWm527612KAyjFTy7hCDiNXB3fMfbrr
thanks!

**Comment by dung5ire** [comment]
@coinvf please try again

**Comment by umersaeed1211** [comment]
0x54FbC97734Ba26DC2BAB787135Ec590ae99cF257

**Comment by umersaeed1211** [comment]
0x5a43F01d7Fd369c305f6d06f55d3056ceE8d6803

**Comment by umersaeed1211** [comment]
> > Please give us your address
> 
> 
> 
> my address:  5HLMC1vNUA3TgdoqppWm527612KAyjFTy7hCDiNXB3fMfbrr
> 
> thanks!

This is not my address

**Comment by umersaeed1211** [comment]
5HmDf4CNtdQLwTAYzU7mphyHh1TYLSxJXhERcmWJKe1vEbBT

**Comment by umersaeed1211** [comment]
0xD1A1EF14dD860D5D78C8946F9ddBb6381d707241
