### ISSUE TITLE
node:internal/errors:490     ErrorCaptureStackTrace(err);     Error [ERR_MODULE_NOT_FOUND]: Cannot find package

### ISSUE THREAD

**Issue by L1xus** [5ire-tech/wasm-contract-deployment#14]
Hi, I get this error when I try to deploy the contract.
I know it is something related with the path but I need help on it.
I followed this guide [https://docs.5ire.org/docs/deploysmartcontracts/nativechain_wasm/]
![Screenshot from 2023-03-31 11-11-59](https://user-images.githubusercontent.com/117644284/229105920-90e37081-2543-4df2-856b-000782b1678c.png)

**Comment by dung5ire** [comment]
try `npm install` -> then `node deploy` or `yarn install` -> `node deploy`
