### ISSUE TITLE
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.

### ISSUE THREAD

**Issue by Boulardos** [5ire-tech/wasm-contract-deployment#16]
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	esm 6.3.1	node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
	esm 6.3.1	node_modules/@polkadot/keyring/node_modules/@polkadot/wasm-crypto/

**Comment by dung5ire** [comment]
This is warning issues. Our logic is still working. We will update soon after big update

**Comment by Boulardos** [comment]
ok but thx tx went through for a cost of 7 5ire but no sc deployed. I cloned the repo updated phrase with my seed when run node deplpy.js.
when i check my txs from my address in the dashboard i dont see any sc deployment
could tou send me test token for tests @  5H4kgfk6MH51P17vaZVccjrHgYfJPeddUWvdH8PMZXi4xEPd

**Comment by Boulardos** [comment]
resolved
thx for the 5ire you sent me, it worked this time and cost me 6.2 5ire$

**Comment by dung5ire** [comment]
yep. We have some configuration about token decimal and how to configure our transaction fee. That why our transaction fee is high at this moment. We already fixed it, but we are about to release big update soon. Please patient
