### ISSUE TITLE
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

### ISSUE THREAD

**Issue by ethbao666** [5ire-tech/wasm-contract-deployment#17]
My address have enough 5ire tokens to supporting pay the gas, but always to notice the error: RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low.

Please the developer resolve the question... thankyou.

**Comment by dung5ire** [comment]
Please give us your address. We will transfer more token that you are able to deploy smart contract . We fixed this issue. Need time to release all features

**Comment by bjshl** [comment]
address:5GhkQEuxYkdVNhh4qDXn855a4W5fERPZM8UeC3joWGMqFfc7
