### ISSUE TITLE
error catch TypeError: Cannot read properties of null (reading 'signAndSend')

### ISSUE THREAD

**Issue by vcrlab** [5ire-tech/wasm-contract-deployment#19]
Hi
wasm-contract-deployment error
PS D:\Testnet\wasm-contract-deployment> yarn install
yarn install v1.22.19
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Done in 16.78s.
PS D:\Testnet\wasm-contract-deployment> node deploy.js
error catch TypeError: Cannot read properties of null (reading 'signAndSend')
    at file:///D:/Testnet/wasm-contract-deployment/deploy.js:50:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by dung5ire** [comment]
Please re-check again. It's working now @vcrlab
