### ISSUE TITLE
Big gas for a smart contract

### ISSUE THREAD

**Issue by velyar** [5ire-tech/wasm-contract-deployment#9]
Hi all.
When creating a smart contract in the native network, about 15 tokens are deducted from the address. Can't we regulate the gas itself when creating a smart contract? If earlier the faucet gave 100 tokens per address, now it gives 5 and thus does not create a smart contract in any way, a message about an insufficient balance.

**Comment by dung5ire** [comment]
We are looking on this issue . Thanks
